services:
  users-db: # Nombre del servicio, usado en la base de datos (comunicacion)
    image: postgres:latest
    container_name: user-db # Nombre del contenedor
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USERS}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - freelance-network

  listings-db: # Nombre del servicio, usado en la base de datos (comunicacion)
    image: postgres:latest
    container_name: listing-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_LISTING}
    ports:
      - "5434:5432" # expuesta en 5434 para que no choque con users-db
    volumes:
      - listings-db-data:/var/lib/postgresql/data
    networks:
      - freelance-network

  users-service:
    container_name: users-service
    build:
      context: ./backend
      dockerfile: users-service/Dockerfile
    depends_on:
      - users-db
    ports:
      - "5001:5001"
    working_dir: /app
    command: pnpm start
    env_file:
      - ./backend/users-service/.env.production
    networks:
      - freelance-network

  listings-service:
    container_name: listings-service
    build:
      context: ./backend
      dockerfile: listings-service/Dockerfile
    depends_on:
      - listings-db
    ports:
      - "5002:5002"
    working_dir: /app
    command: pnpm start
    env_file:
      - ./backend/listings-service/.env.production
    networks:
      - freelance-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./backend/api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - users-service
      - listings-service
    working_dir: /app
    command: pnpm start
    networks:
      - freelance-network
    volumes:
      - ./backend/api-gateway/src:/app/src
    env_file:
      - ./backend/api-gateway/.env.production

volumes:
  postgres-data:
  listings-db-data:

networks:
  freelance-network:
    driver: bridge
